-- File auto generated by purescript-bridge! --
module WebRepl.App where

import Prim (String)
import WebRepl.Exn (ServiceError)

import Data.Generic (class Generic)


data ServerCommand =
    CompileExpr String
  | ClearState 

derive instance genericServerCommand :: Generic ServerCommand

data ServerReply =
    PrintStatement String
  | ReportError ServiceError

derive instance genericServerReply :: Generic ServerReply

