-- File auto generated by purescript-bridge! --
module WebRepl.Exn where

import Prim (String)

import Data.Generic (class Generic)


data ServiceError =
    ParseError String
  | BadRequest String
  | EvalError EvalError

derive instance genericServiceError :: Generic ServiceError

data EvalError =
    VarNotFound String

derive instance genericEvalError :: Generic EvalError

